### ISSUE TITLE
花名册

### ISSUE THREAD

**Issue by Hagb** [QYBoai/ITSociety#1]
@QYBoai/itsociety 
七(4)于梓濠 @liuzibin 
八(1)王芳菲 @HeyAxiao
八(1)骆言 @ARX233 
八(6)祝恺晖 @ZhuKaihui
八(6)吴羽 @what-can-be-name
高一(2)郭俊余 @Hagb

**Comment by liuzibin** [comment]
我是七(4)于梓濠

**Comment by ARX233** [comment]
我是八一骆言

**Comment by Hagb** [comment]
我只知道社团里的人还有在GitHub的吗？

**Comment by ARX233** [comment]
there
